flowchart TD
    A[Transformación Box-Cox] --> B[Reducción Dimensionalidad PCA]
    B --> C[Comparación métodos de agrupación Val. Interna]
    C --> D[Análisis de Estabilidad Jaccard]
    D --> E[Selección de método de agrupación]
    E --> F[Segmentación]